# Generated by Django 4.2 on 2023-06-02 12:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, choices=[('actor', 'Actor'), ('writer', 'Writer'), ('director', 'Director')], max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos')),
            ],
        ),
    ]
